version: '3.1'
services:
  db:
    container_name: db
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3320:3306
    environment:
      MYSQL_DATABASE: shortener
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: users_service
      MYSQL_PASSWORD: 123
    volumes: 
      - ./docker/mysql/datadir:/var/lib/mysql
      - ./docker/mysql/script:/docker-entrypoint-initdb.d
  node:
    image: node:14.5.0
    working_dir: /app/api
    command: 
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    ports:
     - "8125:8125"
    depends_on:
     - db
    restart: on-failure
    environment:
     - HOST=db
     - PORT=8125
     - HOSTNAME=0.0.0.0
     - DB_USER=users_service
     - DB_PASS=123
     - DB_DATABASE=shortener
    volumes:
     - ./src:/app/api
  pma:
    image: phpmyadmin:latest
    restart: on-failure
    environment:
      - PMA_HOST=db
      - PMA_USER=users_service
      - PMA_PASSWORD=123
      - MYSQL_ROOT_PASSWORD=1234
      - PMA_ARBITRARY=1
    ports:
      - "8080:80"
